### ISSUE TITLE
Localhost proxy

### ISSUE THREAD

**Issue by jnmorse** [chingu-voyages/v9-geckos-team-07#5]
In the client side `create-react-app` package.json we should add the following.

```json
    "proxy": {
        "/auth/google": {
            "target": "http://localhost:4000"
        },
        "/api/*": {
            "target": "http://localhost:4000"
        }
    },
```

While developing locally this will redirect to the "backend" server for the `/auth` and `/api` routes. And locally will need to run both the backend server and frontend.

I'm sorta basing this around a tutorial I did a while ago that you can see the code here https://github.com/jnmorse/udemy-emaily-server

Eventually, when a user clicks a link/button to login they will be redirected via the `/api/google` route and logged in.

To get the current user that is logged in, we can make a request to `/api/current_user` that will return the user object.

**Comment by jnmorse** [comment]
So apparently this method was changed since I last used it. In order for this to work now, rather than add the proxy to the package.json file, you will add a setupProxy.js file in the /src folder with

```js
module.exports = app => {
  app.use(proxy('/auth', { target: 'http://localhost:4000/' }))
  app.use(proxy('/api', { target: 'http://localhost:4000/' }))
}
```

Primarily cause of using /auth as a route.

**Comment by shakurtrammel** [comment]
Got it. I'll get this wired up.
